const lionKing = [
  {
    name: 'Simba',
    img: './img/simba.jpg',
    species: 'Lion',
    role: 'Main hero',
    description: 'Son of Mufasa and Sarafina',
    age: 2,
    gender: 'Male',
  },
  {
    name: 'Mufasa',
    img: './img/mufasa.webp',
    species: 'Lion',
    role: 'King',
    description: 'Simba father',
    age: 8,
    gender: 'Male',
  },
  {
    name: 'Nala',
    img: './img/nala.webp',
    species: 'Lion',
    role: 'Simba girlfriend',
    description: 'Simba childhood friend',
    age: 3,
    gender: 'Female',
  },
  {
    name: 'Timon',
    img: './img/timon.jpg',
    species: 'Marmot',
    role: 'Simba friend',
    description: 'Funny and witty marmot',
    age: 1,
    gender: 'Male',
  },
  {
    name: 'Pumba',
    img: './img/pumba.webp',
    species: 'Pig',
    role: 'Simba friend',
    description: 'Funny and witty pig',
    age: 4,
    gender: 'Male',
  },
  {
    name: 'Rafiki',
    img: './img/rafiki.jpg',
    species: 'Monkey',
    role: 'Sage and Priest',
    description: 'Monkey playing role of a sage',
    age: 10,
    gender: 'Male',
  },

]
